name: MacOS Python tests

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Swig install
      run: brew install swig
    - name: Configure
      run: cmake -S . -Bbuild -DBUILD_TESTING=ON -DBUILD_PYTHON=ON -DBUILD_SHARED_LIBS=ON
    - name: Build
      run: cmake --build build --config Release --target all -v
    - name: Test
      run: cd build && ctest --verbose
    - name: Install
      run: cmake --build build --config Release --target install -v -- DESTDIR=install
